@echo off
title PUSH + UPDATE SOURCE SCRIPT
echo Setting Path...
set gitdir=C:\Users\User 1\Downloads\PortableGit
set path=%gitdir%\cmd;%path%
echo Adding Files...
git add .
echo Commiting Source...
git commit -m "Updated Source"
echo Adding Origin (if not already added)...
git remote add origin https://github.com/AlexDev404/misc-prog.git
echo Verifying Remote...
git remote -v
echo Pushing to Origin...
git push origin master
echo Done!
pause